name: AntiHack
version: '${project.version}'
main: me.ikevoodoo.antihack.Main
api-version: 1.13
authors: [ IkeVoodoo ]
description: Spigot version of AntiHack, An atempt at fixing the Log4Shell exploit
