name: Me.ikevoodoo
version: '${project.version}'
main: antihackspigot.me.ikevoodoo.Me.ikevoodoo
api-version: 1.13
authors: [ IkeVoodoo ]
description: Spigot version of AntiHack, An atempt at fixing the Log4Shell exploit
